{% set name = "satgen" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JiangFangzhou/SatGen/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d5222060a7981cd1e606252bafa3a3e46ac188f7ec9fe791c548ed6a66eed106

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - fast-histogram
    - cosmolopy

test:
  # no pip check since requirements in setup.py are wrong
  requires:
    - python {{ python_min }}
  imports:
    - SatGen

about:
  home: https://github.com/JiangFangzhou/SatGen
  summary: 'A semi-analytical satellite galaxy and dark matter halo generator'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
